slrn pre0.9.9 changes 100-101 100. src/config.hin,configure: Added the appropriate checks to enable      IPv6 support (Joerg Sommer) 101. src/misc.c: In queries, the default values of response characters      were not being properly highlighted.
git-svn-id: https://slrn.svn.sourceforge.net/svnroot/slrn/trunk@269 b66dfc27-5e3b-0410-ac45-e82dab92a7d9

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8442,14 +8442,26 @@ done
 
 
 
+
+
+
+
+
+
 for ac_header in \
+direct.h \
 stdlib.h \
 unistd.h \
 memory.h \
 fcntl.h \
+sys/fcntl.h \
+sys/dir.h \
+ndir.h \
+sys/ndir.h \
 malloc.h \
 termios.h \
 sys/socket.h \
+sys/time.h \
 socket.h \
 sys/wait.h \
 netinet/in.h \
@@ -9007,6 +9019,68 @@ _ACEOF
 fi
 
 
+#dnl Eventually, this should go away.  We don't need long doubles.  It is
+#dnl here for the snprintf code.
+{ echo "$as_me:$LINENO: checking for long double" >&5
+echo $ECHO_N "checking for long double... $ECHO_C" >&6; }
+if test "${ac_cv_type_long_double+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+typedef long double ac__type_new_;
+int
+main ()
+{
+if ((ac__type_new_ *) 0)
+  return 0;
+if (sizeof (ac__type_new_))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_type_long_double=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_type_long_double=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_type_long_double" >&5
+echo "${ECHO_T}$ac_cv_type_long_double" >&6; }
+
+
+
+
+
+
+
 
 
 
@@ -9028,9 +9102,14 @@ fi
 for ac_func in \
 memset \
 memcpy \
+memcmp \
+memchr \
 putenv \
 getcwd \
 getdomainname \
+getaddrinfo \
+getnameinfo \
+gettimeofday \
 sigaction \
 sigemptyset \
 sigprocmask \
